### ISSUE TITLE
Scaling bug on macOS Big Sur 11.2.3

### ISSUE THREAD

**Issue by mitchazj** [opentk/opentk#1296]
### Description

Running any GameWindow (from the examples at https://github.com/opentk/LearnOpenTK) produces this behaviour:

https://user-images.githubusercontent.com/15032956/120263237-9f88c100-c2de-11eb-81b0-4eb5dfd37d90.mp4

1. Window opens fine, but content is entirely boxed into the bottom left corner
2. Moving the macOS window slightly with the mouse corrects the issue
3. Note that window is not frozen, the colors will update on the square and it will receive input even if I do not move the window.

### Repro steps

Open any example from https://github.com/opentk/LearnOpenTK and attempt to run on macOS Big Sur.
You may need to install https://github.com/CoreCompat/libgdiplus-packaging to make GDI work correctly with textures for some of the examples.

I had to use these settings to get the window working:
```csharp
NativeWindowSettings nativeWindowSettings = new NativeWindowSettings() {
    Size = new Vector2i(800, 600),
    Title = "mricraft - native",
};

nativeWindowSettings.Flags = ContextFlags.ForwardCompatible;
nativeWindowSettings.Profile = ContextProfile.Core;
nativeWindowSettings.APIVersion = new Version(4, 1);

using (Game game = new Game(GameWindowSettings.Default, nativeWindowSettings)) {
    game.Run(); // aim for 60fps
}
```

### Expected behavior

The window should open with correct scaling immediately (especially when the window opens and captures the mouse, it is not possible to move the window quickly to fix scaling)

### Actual behavior

The window opens with all the content pushed into the bottom left corner.
Interestingly, clearing the window with OpenGL still behaves correctly and colors the whole screen.

### Related information 

* Operating system (macOS Big Sur 11.2.3, intel i5 mac)
* SDL or Native backend
* What version of OpenTK (Installer, NuGet, Source Code) nuget `<PackageReference Include="opentk" Version="4.6.3" />`
* What runtime (.NET Framework, CoreCLR, Mono) .net core
* Workarounds (if any) none found as of yet

**Comment by mitchazj** [comment]
As a temporary workaround, full-screening the window (if that's suitable for your application) seems to bypass this issue well.
If your application needs to be windowed however, this is not an ideal solution.

**Comment by KOLLSOFT** [comment]
same issue on M1 macOS Monterey12.0.1,  Window crash with FullScreen.
crash stack-trace:
Unhandled exception. OpenTK.Windowing.GraphicsLibraryFramework.GLFWException: Cocoa: Failed to find service port for display
   at OpenTK.Windowing.Desktop.GLFWProvider.<>c.<.cctor>b__5_0(ErrorCode errorCode, String description)

**Comment by TheFlamingCrab** [comment]
Hi! Not sure if this will help, but I fixed this issue by removing the line GL.ViewPort Line in OnResize.

**Comment by Lancelotbronner** [comment]
Still happening on Ventura 13.1 M1, except resizing the window doesn't help. I have to go fullscreen then back to windowed and it'll work until the window is resized again.

Produces the following log:

```log
1   HIToolbox                           0x00000001b0d205c8 _ZN15MenuBarInstance22EnsureAutoShowObserverEv + 120
2   HIToolbox                           0x00000001b0d20188 _ZN15MenuBarInstance14EnableAutoShowEv + 60
3   HIToolbox                           0x00000001b0c8d8bc _ZN15MenuBarInstance21UpdateAggregateUIModeE21MenuBarAnimationStylehhh + 1184
4   HIToolbox                           0x00000001b0d20004 _ZN15MenuBarInstance19SetFullScreenUIModeEjj + 180
5   AppKit                              0x00000001aab16008 -[NSApplication _setPresentationOptions:instance:flags:] + 956
6   AppKit                              0x00000001aa9abbb0 -[NSApplication _updateFullScreenPresentationOptionsForInstance:] + 404
7   CoreFoundation                      0x00000001a75cd570 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 148
8   CoreFoundation                      0x00000001a766b054 ___CFXRegistrationPost_block_invoke + 88
9   CoreFoundation                      0x00000001a766af9c _CFXRegistrationPost + 440
10  CoreFoundation                      0x00000001a759eb74 _CFXNotificationPost + 708
11  Foundation                          0x00000001a848c72c -[NSNotificationCenter postNotificationName:object:userInfo:] + 88
12  AppKit                              0x00000001aab1658c spacesNotificationHandler + 96
13  SkyLight                            0x00000001ac2004dc _ZN12_GLOBAL__N_123notify_datagram_handlerEj15CGSDatagramTypePvmS1_ + 896
14  SkyLight                            0x00000001ac52c4c4 _ZN21CGSDatagramReadStream26dispatchMainQueueDatagramsEv + 228
15  SkyLight                            0x00000001ac52c3c0 ___ZN21CGSDatagramReadStream15mainQueueWakeupEv_block_invoke + 28
16  libdispatch.dylib                   0x00000001a73709dc _dispatch_call_block_and_release + 32
17  libdispatch.dylib                   0x00000001a7372504 _dispatch_client_callout + 20
18  libdispatch.dylib                   0x00000001a7380d1c _dispatch_main_queue_drain + 928
19  libdispatch.dylib                   0x00000001a738096c _dispatch_main_queue_callback_4CF + 44
20  CoreFoundation                      0x00000001a7619d50 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
21  CoreFoundation                      0x00000001a75d77d0 __CFRunLoopRun + 2036
22  CoreFoundation                      0x00000001a75d6888 CFRunLoopRunSpecific + 612
23  HIToolbox                           0x00000001b0cabfa0 RunCurrentEventLoopInMode + 292
24  HIToolbox                           0x00000001b0cabde4 ReceiveNextEventCommon + 672
25  HIToolbox                           0x00000001b0cabb2c _BlockUntilNextEventMatchingListInModeWithFilter + 72
26  AppKit                              0x00000001aa858424 _DPSNextEvent + 632
27  AppKit                              0x00000001aa8575b4 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 728
28  libglfw.3.dylib                     0x000000010125f2c8 _glfwPlatformPollEvents + 220
29  ???                                 0x0000000103321b04 0x0 + 4348582660
30  ???                                 0x00000001032f1714 0x0 + 4348385044
31  ???                                 0x00000001032d0c8c 0x0 + 4348251276
32  libcoreclr.dylib                    0x0000000101634074 CallDescrWorkerInternal + 132
33  libcoreclr.dylib                    0x00000001014a9fa4 _ZN18MethodDescCallSite16CallTargetWorkerEPKmPmi + 852
34  libcoreclr.dylib                    0x00000001013ade68 _Z7RunMainP10MethodDescsPiPP8PtrArray + 640
35  libcoreclr.dylib                    0x00000001013ae17c _ZN8Assembly17ExecuteMainMethodEPP8PtrArrayi + 396
36  libcoreclr.dylib                    0x00000001013d57ac _ZN8CorHost215ExecuteAssemblyEjPKDsiPS1_Pj + 536
37  libcoreclr.dylib                    0x000000010139b844 coreclr_execute_assembly + 192
38  libhostpolicy.dylib                 0x0000000100cad52c _Z19run_app_for_contextRK20hostpolicy_context_tiPPKc + 1072
39  libhostpolicy.dylib                 0x0000000100cae290 corehost_main + 240
40  libhostfxr.dylib                    0x0000000100c387f4 _ZN10fx_muxer_t24handle_exec_host_commandERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEERK19host_startup_info_tS8_RKNS0_13unordered_mapI13known_optionsNS0_6vectorIS6_NS4_IS6_EEEE18known_options_hashNS0_8equal_toISD_EENS4_INS0_4pairIKSD_SG_EEEEEEiPPKci11host_mode_tbPciPi + 1328
41  libhostfxr.dylib                    0x0000000100c378e8 _ZN10fx_muxer_t7executeENSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEEiPPKcRK19host_startup_info_tPciPi + 860
42  libhostfxr.dylib                    0x0000000100c344d4 hostfxr_main_startupinfo + 152
43  dotnet                              0x0000000100ad14e0 _Z9exe_startiPPKc + 1176
44  dotnet                              0x0000000100ad1698 main + 160
45  dyld                                0x00000001a71cfe50 start + 2544
1   HIToolbox                           0x00000001b0e46d4c _ZN15MenuBarInstance21IsAutoShowHideAllowedEv + 284
2   HIToolbox                           0x00000001b0d20230 _ZN15MenuBarInstance24UpdateAutoShowVisibilityE5Pointh + 40
3   HIToolbox                           0x00000001b0c8d3b8 _ZN15MenuBarInstance16ForEachMenuBarDoEU13block_pointerFvPS_E + 244
4   HIToolbox                           0x00000001b0d208a0 _ZN15MenuBarInstance20AutoShowHideObserverEjP14OpaqueEventRefPv + 216
5   HIToolbox                           0x00000001b0c83cd0 _NotifyEventLoopObservers + 176
6   HIToolbox                           0x00000001b0cb7bb0 PostEventToQueueInternal + 696
7   HIToolbox                           0x00000001b0cb9340 _ZL29CreateAndPostEventWithCGEventP9__CGEventjhP17__CFMachPortBoost + 460
8   HIToolbox                           0x00000001b0cc5c28 _ZL15Convert1CGEventh + 264
9   HIToolbox                           0x00000001b0cc5ab0 _ZL16MainLoopObserverjP14OpaqueEventRefPv + 56
10  HIToolbox                           0x00000001b0c83cd0 _NotifyEventLoopObservers + 176
11  HIToolbox                           0x00000001b0cabf60 RunCurrentEventLoopInMode + 228
12  HIToolbox                           0x00000001b0cabc30 ReceiveNextEventCommon + 236
13  HIToolbox                           0x00000001b0cabb2c _BlockUntilNextEventMatchingListInModeWithFilter + 72
14  AppKit                              0x00000001aa858424 _DPSNextEvent + 632
15  AppKit                              0x00000001aa8575b4 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 728
16  libglfw.3.dylib                     0x000000010125f288 _glfwPlatformPollEvents + 156
17  ???                                 0x0000000103321b04 0x0 + 4348582660
18  ???                                 0x00000001032f1714 0x0 + 4348385044
19  ???                                 0x00000001032d0c8c 0x0 + 4348251276
20  libcoreclr.dylib                    0x0000000101634074 CallDescrWorkerInternal + 132
21  libcoreclr.dylib                    0x00000001014a9fa4 _ZN18MethodDescCallSite16CallTargetWorkerEPKmPmi + 852
22  libcoreclr.dylib                    0x00000001013ade68 _Z7RunMainP10MethodDescsPiPP8PtrArray + 640
23  libcoreclr.dylib                    0x00000001013ae17c _ZN8Assembly17ExecuteMainMethodEPP8PtrArrayi + 396
24  libcoreclr.dylib                    0x00000001013d57ac _ZN8CorHost215ExecuteAssemblyEjPKDsiPS1_Pj + 536
25  libcoreclr.dylib                    0x000000010139b844 coreclr_execute_assembly + 192
26  libhostpolicy.dylib                 0x0000000100cad52c _Z19run_app_for_contextRK20hostpolicy_context_tiPPKc + 1072
27  libhostpolicy.dylib                 0x0000000100cae290 corehost_main + 240
28  libhostfxr.dylib                    0x0000000100c387f4 _ZN10fx_muxer_t24handle_exec_host_commandERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEERK19host_startup_info_tS8_RKNS0_13unordered_mapI13known_optionsNS0_6vectorIS6_NS4_IS6_EEEE18known_options_hashNS0_8equal_toISD_EENS4_INS0_4pairIKSD_SG_EEEEEEiPPKci11host_mode_tbPciPi + 1328
29  libhostfxr.dylib                    0x0000000100c378e8 _ZN10fx_muxer_t7executeENSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEEiPPKcRK19host_startup_info_tPciPi + 860
30  libhostfxr.dylib                    0x0000000100c344d4 hostfxr_main_startupinfo + 152
31  dotnet                              0x0000000100ad14e0 _Z9exe_startiPPKc + 1176
32  dotnet                              0x0000000100ad1698 main + 160
33  dyld                                0x00000001a71cfe50 start + 2544
1   HIToolbox                           0x00000001b0cab90c _ZN15MenuBarInstance22RemoveAutoShowObserverEv + 44
2   HIToolbox                           0x00000001b0cc3214 SetMenuBarObscured + 120
3   HIToolbox                           0x00000001b0cca390 _ZN13HIApplication11FrontUILostEv + 44
4   HIToolbox                           0x00000001b0cc304c _ZN13HIApplication15HandleActivatedEP14OpaqueEventRefhP15OpaqueWindowPtrh + 528
5   HIToolbox                           0x00000001b0cbcf70 _ZN13HIApplication13EventObserverEjP14OpaqueEventRefPv + 204
6   HIToolbox                           0x00000001b0c83cd0 _NotifyEventLoopObservers + 176
7   HIToolbox                           0x00000001b0cbc96c AcquireEventFromQueue + 432
8   HIToolbox                           0x00000001b0cabc84 ReceiveNextEventCommon + 320
9   HIToolbox                           0x00000001b0cabb2c _BlockUntilNextEventMatchingListInModeWithFilter + 72
10  AppKit                              0x00000001aa858424 _DPSNextEvent + 632
11  AppKit                              0x00000001aa8575b4 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 728
12  libglfw.3.dylib                     0x000000010125f2c8 _glfwPlatformPollEvents + 220
13  ???                                 0x0000000103321b04 0x0 + 4348582660
14  ???                                 0x00000001032f1714 0x0 + 4348385044
15  ???                                 0x00000001032d0c8c 0x0 + 4348251276
16  libcoreclr.dylib                    0x0000000101634074 CallDescrWorkerInternal + 132
17  libcoreclr.dylib                    0x00000001014a9fa4 _ZN18MethodDescCallSite16CallTargetWorkerEPKmPmi + 852
18  libcoreclr.dylib                    0x00000001013ade68 _Z7RunMainP10MethodDescsPiPP8PtrArray + 640
19  libcoreclr.dylib                    0x00000001013ae17c _ZN8Assembly17ExecuteMainMethodEPP8PtrArrayi + 396
20  libcoreclr.dylib                    0x00000001013d57ac _ZN8CorHost215ExecuteAssemblyEjPKDsiPS1_Pj + 536
21  libcoreclr.dylib                    0x000000010139b844 coreclr_execute_assembly + 192
22  libhostpolicy.dylib                 0x0000000100cad52c _Z19run_app_for_contextRK20hostpolicy_context_tiPPKc + 1072
23  libhostpolicy.dylib                 0x0000000100cae290 corehost_main + 240
24  libhostfxr.dylib                    0x0000000100c387f4 _ZN10fx_muxer_t24handle_exec_host_commandERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEERK19host_startup_info_tS8_RKNS0_13unordered_mapI13known_optionsNS0_6vectorIS6_NS4_IS6_EEEE18known_options_hashNS0_8equal_toISD_EENS4_INS0_4pairIKSD_SG_EEEEEEiPPKci11host_mode_tbPciPi + 1328
25  libhostfxr.dylib                    0x0000000100c378e8 _ZN10fx_muxer_t7executeENSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEEiPPKcRK19host_startup_info_tPciPi + 860
26  libhostfxr.dylib                    0x0000000100c344d4 hostfxr_main_startupinfo + 152
27  dotnet                              0x0000000100ad14e0 _Z9exe_startiPPKc + 1176
28  dotnet                              0x0000000100ad1698 main + 160
29  dyld                                0x00000001a71cfe50 start + 2544
```

**Comment by NiiloMi** [comment]
It seems that the viewport is at half scale on MacOs. 
To fix it you can just double your scale like this in the OnResize function: GL.Viewport(0, 0, Size.X * 2, Size.Y * 2);

**Comment by Lancelotbronner** [comment]
> It seems that the viewport is at half scale on MacOs. 
> 
> To fix it you can just double your scale like this in the OnResize function: GL.Viewport(0, 0, Size.X * 2, Size.Y * 2);

This is the workaround I'm currently using, but the real issue is OpenTK not handling scaling.

This is not platform-specific so a few #if won't be enough for the job. We'd need either a way to retrieve the screen scaling or have scaling already handled.

**Comment by DigitalBox98** [comment]
Until this bug is fixed, I've proposed a solution to handle the scale factor here : https://github.com/opentk/LearnOpenTK/issues/88

**Comment by NogginBops** [comment]
This has been solved in 4.8.2 with the introduction of the `FramebufferSize` property and the `OnFramebufferResize` callback which reports the correct values for different scaling factors.

**Comment by NogginBops** [comment]
Feel free to open again if this solution does not work

**Comment by DigitalBox98** [comment]
Ok perfect, using the below command to retrieve the fs.X and fs.Y on the window for the new buffer is fine:
Vector2i fs = this.FramebufferSize;

Thanks a lot !
