### ISSUE TITLE
Leaking of Mach Ports on OS X

### ISSUE THREAD

**Issue by joelhoover** [opentk/opentk#407]
I have recently come across an issue on OS X, where creating and destroying an OpenGL context is leaking mach ports. This issue can reliably be reproduced with one of the following methods (with the second method just being a more refined version of the first).

```
void machLeak1() {
  while(true) {
    (new GameWindow()).Dispose();
  }
}

void machLeak2() {
  OpenTK.Toolkit.Init();
  var wi = OpenTK.Platform.Utilities.CreateMacOSWindowInfo(IntPtr.Zero);
  while(true) {
    var context = new OpenTK.GraphicsContext(OpenTK.Graphics.GraphicsMode.Default, wi);
    context.MakeCurrent(wi);
    context.Dispose();
  }
}
```

If you run one of these pieces of code and watch the "Ports" column in Activity Monitor for the process, you can see the number of ports increases unbounded as the code runs, until it crashes with either an `OpenTK.GraphicsException` "Failed to construct NSOpenGLContext", or sometimes with a native crash, such as [Mach_Port_Leak_Crash.txt](https://github.com/opentk/opentk/files/336077/Mach_Port_Leak_Crash.txt) or [Mach_Port_Leak_Crash2.txt](https://github.com/opentk/opentk/files/336078/Mach_Port_Leak_Crash2.txt).

I did some counting of iterations, and it works out that 2 mach ports are being leaked for ever iteration in one of the above loops. It will also crash after about 750 iterations.

It really just looks like something is forgotten to be released, but I'm not familiar enough with the low-level API here to know specifically how to fix this problem.

Also, here is my system setup:
OS X 10.11.3
OpenTK master (01e0027580f5930083da40ea43e5721654efd837)
Mono 4.4.0
Xamarin Studio 5.10.3

**Comment by cra0zy** [comment]
Are you using SDL or Native backend?

**Comment by joelhoover** [comment]
I am using the Native backend.

I just installed SDL now, and the SDL backend does not have this issue.

**Comment by varon** [comment]
Steps to debug:
1) Figure out where we're allocating the ports
2) Release the ports in some IDisposable implementation

If someone has any ideas on where to start here, I can possibly take a look at this.

**Comment by Nihlus** [comment]
I've determined that pointers to mach ports (CFMachPortRef deffed to an IntPtr) are being created in Platform/MacOS/HIDInput.cs:239 in order to monitor mouse events.

According to the implemented Dispose method, 
`if (MouseEventTapSource != IntPtr.Zero)
{
	// Note: releasing the mach port (tap source)
	// automatically releases the event tap.
	CF.RunLoopRemoveSource(RunLoop, MouseEventTapSource, CF.RunLoopModeDefault);
	CF.CFRelease(MouseEventTapSource);
	MouseEventTapSource = IntPtr.Zero;
}`

it is releasing the tap, but perhaps that is not the case anymore. I am not seeing any explicit information in the Apple documentation that that is expected behaviour. @joelhoover could you try adding 

`if (MouseEventTap != IntPtr.Zero)
{
	CF.CFRelease(MouseEventTap);
	MouseEventTap = IntPtr.Zero;
}`

in Platform/MacOS/HIDInput.cs at 1699 and testing if the issue is still present?

**Comment by varon** [comment]
@Nihlus  - Doubt he's still around. I can try to do this when I get some time.

**Comment by joelhoover** [comment]
@varon Don't worry, I'm still around. 👍 

@Nihlus I've just tried the MouseEventTap fix, and it did not improve the situation at all. It seems that the HIDInput is actually only created once doing the entire program, so it can't be the source of the the leak.

Upon further investigation, I was able to find that the two ports are allocated during the native call to initialize the `NSOpenGLContext` (https://github.com/opentk/opentk/blob/develop/src/OpenTK/Platform/MacOS/CocoaContext.cs#L125):
```C#
// File: Platform/MacOS/CocoaContext.cs
private void CreateContext(GraphicsMode mode, CocoaWindowInfo cocoaWindow, IntPtr shareContextRef, int majorVersion, int minorVersion, bool fullscreen)
{
    // ...

    // Create context
    var context = Cocoa.SendIntPtr(NSOpenGLContext, Selector.Alloc);
    context = Cocoa.SendIntPtr(context, Selector.Get("initWithFormat:shareContext:"), pixelFormat, shareContextRef);

   // ...
}
```
I don't see anything in `CocoaContext.Dispose` that directly releases the `NSOpenGLContext`, but if my (limited) understanding is correct, it should be released when its enclosing view is released. At the very least, I was unable to find anything online that suggested doing anything special to clean up the OpenGL context.

While looking online, however, I came across [this example program](https://github.com/chadversary/gl-examples/blob/master/src/cocoa/create-cocoa-custom-nsopenglview-with-nsopenglcontext/main.m) which wraps the main function in an autorelease pool, and mentions that the documentation for `NSApplication` mentions that Cocoa calls from the main function should do so ([documentation link](https://developer.apple.com/documentation/appkit/nsapplication), last paragraph of the Overview section). This got me curious, and so I decided to attempt this in the C# application to see if it helps. I had to change the access modifiers on a bunch of classes to write this outside of the OpenTK project (just for testing), but I arrived at the following code which has no leaks.

```C#
private static void machLeakPoolFixed()
{
    var AutoreleasePool = OpenTK.Platform.MacOS.Class.NSAutoreleasePool;
    while(true) {
        var pool = OpenTK.Platform.MacOS.Cocoa.SendIntPtr(AutoreleasePool, OpenTK.Platform.MacOS.Selector.Get("alloc"));
        pool = OpenTK.Platform.MacOS.Cocoa.SendIntPtr(pool, OpenTK.Platform.MacOS.Selector.Get("init"));

        (new GameWindow()).Dispose();

        OpenTK.Platform.MacOS.Cocoa.SendVoid(pool, OpenTK.Platform.MacOS.Selector.Get("drain"));
    }
}
```

Additionally, if we move the the `NSAutoreleasePool` outside the loop, then the leak returns.

```C#
private static void machLeakPoolFail()
{
    var AutoreleasePool = OpenTK.Platform.MacOS.Class.NSAutoreleasePool;
    var pool = OpenTK.Platform.MacOS.Cocoa.SendIntPtr(AutoreleasePool, OpenTK.Platform.MacOS.Selector.Get("alloc"));
    pool = OpenTK.Platform.MacOS.Cocoa.SendIntPtr(pool, OpenTK.Platform.MacOS.Selector.Get("init"));

    while(true) {
        (new GameWindow()).Dispose();
    }

    // Will never execute:
    OpenTK.Platform.MacOS.Cocoa.SendVoid(pool, OpenTK.Platform.MacOS.Selector.Get("drain"));
}
```

So, it seems like the `NSOpenGLContext` is not released unless the pool that was active while it was constructed is drained. I am not familiar enough with Objective-C/Cocoa nor OpenTK to know the best way to handle this, whether we can directly specify it should be released in `Dispose`, or if we do need to create an `NSAutoreleasePool` that contains all of the Cocoa calls for the `CocoaContext`, and is then drained by `Dispose`.

**Comment by Nihlus** [comment]
@joelhoover Fantastic work. I don't have a mac myself, unfortunately, but I'll see about implementing this fix in the library and getting someone else to test it :)

**Comment by Nihlus** [comment]
@joelhoover I've implemented the fix in https://github.com/Nihlus/opentk/tree/cocoa-machport-leak-fix - could you pull it and see if works? I wrapped the Cocoa NativeWindow implementation in the autorelease block.

**Comment by joelhoover** [comment]
I can confirm that this commit fixes the looped game window case (`machLeak1` in the original post). However, as you suspected, this does not fix the issue if one creates the `CocoaContext` directly (`machLeak2`). I've done some more research and testing and found out several additional things: first, it seems that autorelease pools are intended to form a stack, and so individual pools should be scoped to a particular block of code. From [the documentation](https://developer.apple.com/documentation/foundation/nsautoreleasepool):

> You should always drain an autorelease pool in the same context (invocation of a method or function, or body of a loop) that it was created.

So in general, the correct way to implement the pools is to have one surrounding every scope in which we interact with Cocoa. Upon further testing however, I found that we only need to wrap `CocoaContext.Dispose` in the autorelease pool; in particular, we need to wrap the following four lines:
```C#
if (IsCurrent)
    Cocoa.SendVoid(NSOpenGLContext, Selector.Get("clearCurrentContext"));
Cocoa.SendVoid(Handle.Handle, Selector.Get("clearDrawable"));
Cocoa.SendVoid(Handle.Handle, Selector.Get("release"));
```
Playing around with it more, I also found that simply doing two `release`s also fixes the problem. So it seems like what is happening is there is some retain/autorelease pair on the `NSOpenGLContext` that occurs during the few lines above.  So, either creating a pool to catch the autorelease, or forcing a double release, causes the `NSOpenGLContext` to be properly deallocated. However, the double release is very hacky and the autorelease pool is definitely the preferred implementation.

As an additional note, it may be worth adding an autorelease pool class in C# that can be used in a `using` statement, to really communicate the scoped nature of the pool. However, that may be overkill for this one fix, and it seems like OpenTK does not currently use any other autorelease pools (although this may be indicative of other leaks?).

**Comment by Nihlus** [comment]
@joelhoover I've moved the current fix to the context instead - could you please test it again and see if both test cases are fixed? 

An autorelease class would definitely be the preferred way to go if we do a refactoring run in the future, but I'm not familiar enough with Objective-C and the MacOS API to do more than basic tasks with it, I'm afraid.

**Comment by joelhoover** [comment]
So the implementation with the autorelease pool in the `CocoaContext` as is currently in branch does fix the leaking issue, but it still doesn't ensure the autorelease pool is scoped to a specific code block. I've tested to to see how much of an issue this can be, and it is rather severe, crashing the application if the autorelease pools (and thus, with the current fix, `CocoaContext`) are created and destroyed in a non-stack like order (e.g. create context1, create context2, destroy contex1, destroy context2).

All we really need for this fix is to wrap the few lines that have Cocoa API calls in `CocoaContext.Dispose()` by putting the autorelease pool `alloc` and `init` before and the `drain` after.

**Comment by Nihlus** [comment]
@joelhoover I see the problem. However, if we do this, won't the objects allocated at context creation be excluded from the pool, removing the point of it altogether? My lack of experience with objective C is, unfortunately, severely limiting me here.
