### ISSUE TITLE
Mouse movement not detected on 64-bit mono

### ISSUE THREAD

**Issue by MariusUtheim** [opentk/opentk#718]
### Description

When running mono on 64 bit, the mouse is always registered as being placed in the lower left corner. It does not seem to be a problem when running on 32-bit architecture.

### Repro steps

I created a new console project on visual studio for mac and downloaded OpenTK from nuget. The program contained the following code:

using System;
using OpenTK;

namespace Bug
{
    class MainClass
    {
        public static void Main(string[] args)
        {
            GameWindow window = new GameWindow();
            window.MouseMove += (sender, e) => window.Title = String.Format("{0}, {1}", e.X, e.Y);
            window.Run();
        }
    }
}

### Expected behavior

The title of the window should show the position of the mouse as you move it.

### Actual behavior

When running the program from VS, it works as expected. When changing the architecture of the project to x64, or running mono from the terminal without specifying --arch=32, the MouseMove event is raised exactly once and the title of the window will always be 0, 480.

### Related information 

* Operating system: macOS 10.13.2
* OpenTK version: 2.0.0 (from Nuget)
* Runtime: Mono

**Comment by VPeruS** [comment]
Update to 3.0, should be fixed

**Comment by MariusUtheim** [comment]
I updated to 3.0.0-pre from Nuget and it still doesn't work. Am I doing something wrong?

**Comment by VPeruS** [comment]
pre is a little bit outdated version, try build from github.

**Comment by copygirl** [comment]
You can also try the builds from MyGet. For example, here's my [`NuGet.Config`](https://github.com/copygirl/opentk-mouse-issue/blob/master/NuGet.Config) and [`.csproj`](https://github.com/copygirl/opentk-mouse-issue/blob/master/MouseIssue.csproj).

**Comment by gabereiser** [comment]
this hit me hard the other day when testing a reported bug in my engine.  MacOS 64-bit High Sierra and the mouse wouldn't move.  I would say it's a pretty serious bug. There are a lot of people on 2.0.0.  When does 3.0.0 hit NuGet?

**Comment by Nihlus** [comment]
@gabereiser We're tracking 3.0.0 release progress on #702.
