### ISSUE TITLE
SizedInternalFormat values missing

### ISSUE THREAD

**Issue by DimaS86** [opentk/opentk#752]
In the latest stable version in OpenGL4 namespace SizedInternalFormat all enum values for RGB* are missing.

* Windows10
* Native backend
* NuGet packet 3.0.0
* .NET Framework 4.7.1

**Comment by Sellmann86** [comment]
the enum values for Depth_Component* are also missing. Found out they are present in PixelInternalFormat, but function calls for texture allocation like TextureStorage2DMultisample do only allow SizedInternalFormat as an argument. Without casting from one to the other it is not possible to allocate a bunch of important texture formats.

Please fix this, since it does not comply to the official OpenGL 4.x specification.

**Comment by VPeruS** [comment]
@DimaS86  which function are you using and which values you cannot find?

**Comment by VPeruS** [comment]
@Sellmann86  can you, please, fill another issue for that.

**Comment by DimaS86** [comment]
I am using the function GL.TextureBuffer
But it doesn't matter, because it seems like that it was simply forgotten to include this values into the enum, so I am using it like
GL.TextureBuffer(PositionDisplacementTextureId[i], (SizedInternalFormat)34837, PositionDisplacementBufferId[i]);
and it is working perfectly fine, but I thought that it would be nice to include this values in the upcoming release, so I reported it.

**Comment by VPeruS** [comment]
You can use missing values from All enums(also casting but without fancy numbers). And thank you for report, indeed some values missing

**Comment by varon** [comment]
@VPeruS - thanks, spot on here.
You can always do casting if this happens. 4.0 should fix it in any case.

**Comment by danielscherzer** [comment]
Please correct me if I'm wrong, but a quick check shows that OpenTK 4.3 still has the RGB* values, like GL_RGB8 missing in SizedInternalFormat.

**Comment by NogginBops** [comment]
Yes this is still a problem in opentk 4. 

We are working on a fix for it for opentk 5. 
The fix should be easily (kind of) be able to integrate into opentk 4 and 3 once the khronos opengl registry has been updated with this enum group.

I'll reopen this issue so that it's more visible.
The workaround is to find the enum you are looking for in the `All` enum and just cast that value to the enum you want.

**Comment by danielscherzer** [comment]
Thanks for the clarification and the workaround!

**Comment by NogginBops** [comment]
Good news. Looks like OpenTK 5 will have this enum with all the currently specified enum values.
https://github.com/KhronosGroup/OpenGL-Registry/pull/459

**Comment by NogginBops** [comment]
This is now fixed in the upcoming 4.7.2 release!
